### ISSUE TITLE
hello-world fn readme update

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-aws-lambda#108]
I've been following the hello-world example in the readme and come across a few subtle differences from updates from AWS and so I intend on popping in the changes to help make the instructions easier to follow.

**Comment by nelsonic** [comment]
@Cleop thanks. yes, the code can use an update to "modern" node.js. 👍

**Comment by Cleop** [comment]
The default fn now uses `async` and I'm not really sure what this is doing but I ran the tests without it and with it and both pass.

```
exports.handler = async (event, context) => {
    console.log('value1 =', event.key1);
    console.log('value2 =', event.key2);
    context.succeed(event.key1 + " " + event.key2);
};
```

I'm going to try to find out but would welcome suggestions from anyone who already has an idea.

**Comment by nelsonic** [comment]
async => `#ModernJS` ... 🙄 (AKA "magic")

**Comment by markhu** [comment]
This repo was supposed to be about learning AWS Lambda, not NodeJS.
Just saying.

**Comment by iteles** [comment]
@markhu It very much is! That's why it's a good idea to not have people 'trip up' or come out of the flow of the tutorial because of something like the code in an example. These are meant to _aid_ people's understanding, not throw up tangential questions that take them off topic.

Updating these makes following the tutorial (and learning AWS Lambda) a smoother experience. 👍

**Comment by markhu** [comment]
Great point. In that spirit, I humbly offer issue #111 / PR #110 that fixes numerous distracting markdown formatting mistakes. To make the source code review less onerous, use Diff settings "Split" & "Hide whitespace." Or just compare/review the rendered doc in another tab/window.

**Comment by Cleop** [comment]
Closing as this has now been updated and merged 👍
